### ISSUE TITLE
go build command failed

### ISSUE THREAD

**Issue by leonardyhuang** [Drafteame/serverless-plugin-go#1]
Hi,

Thank you for forking of https://github.com/mthenw/serverless-go-plugin.

Continuing from issue https://github.com/mthenw/serverless-go-plugin/issues/41, I managed to install your package. However, there was this error (see below) when I ran `sls deploy`. And, I think the command I set on `serverless.yml` was correct, `cmd: 'go build -ldflags="-s -w"'`.

Error log:
```
Error:
Error: error compiling function (cwd: .)
    at Go.execCompilation (file:///Users/leonardy/go/src/anapp/node_modules/serverless-plugin-go/index.js:194:13)
    at async Go.compile (file:///Users/leonardy/go/src/anapp/node_modules/serverless-plugin-go/index.js:146:5)
    at async Promise.all (index 0)
    at async Go.compileFunctions (file:///Users/leonardy/go/src/anapp/node_modules/serverless-plugin-go/index.js:87:5)
    at async PluginManager.runHooks (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.spawn (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (/opt/homebrew/lib/node_modules/serverless/lib/plugins/deploy.js:48:11)
    at async PluginManager.runHooks (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/opt/homebrew/lib/node_modules/serverless/lib/serverless.js:179:5)
    at async /opt/homebrew/lib/node_modules/serverless/scripts/serverless.js:819:9
GoPlugin: Error compiling function (cwd: .): Command failed: go build -ldflags="-s -w" -o .bin/receive receive/main.go
/bin/sh: go: command not found
```

Here is the content of my `serverless.yml`:
```
service: anapp

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64

  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment: ${file(.env.${self:provider.stage}.yml)}

package:
  patterns:
    - '!./**'
    - './bin/**'

functions:
  receive:
    handler: receive/main.go
    events:
      - http:
          path: ${self:custom.functionPath.${self:provider.stage}}/receive
          method: post
    timeout: 30
    memorySize: 128
  verify:
    handler: verify/main.go
    events:
      - http:
          path: ${self:custom.functionPath.${self:provider.stage}}/receive
          method: get
    timeout: 30
    memorySize: 128

custom:
  go:
    baseDir: '.'
    binDir: '.bin'
    cmd: 'go build -ldflags="-s -w"'
    monorepo: false
    env:
      GOOS: 'linux'
      CGO_ENABLED: '0'

plugins:
  - serverless-plugin-go
```

Really appreciate your assistance, thanks.
